name: test
on: 
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      os_type:
        description: Select OS type
        type: choice
        required: true
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - windows-latest

jobs:
  playwright-test:
    runs-on: ${{ github.event.inputs.os_type || 'ubuntu-latest' }}
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
        shell: bash
      - name: install playwright dependencies
        run: npx playwright install --with-deps
        shell: bash
      - name: run playwright test
        run: npm test
        env:
          USER: ${{secrets.USER}}
          PASSWORD: ${{secrets.PASSWORD}}
        shell: bash
      - name: upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 1
      - name: deploy to github pages
        if: github.actor != 'dependabot[bot]'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report